language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install coverage
  - pip install $DJANGO
script:
  - coverage run runtests.py
  - coverage report -m
env:
  - DJANGO="Django>=1.4,<1.5"
  - DJANGO="Django>=1.5,<1.6"
  - DJANGO="Django>=1.6,<1.7"
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="Django>=1.11,<2.0"
  - DJANGO="https://github.com/django/django/archive/master.tar.gz"
matrix:
  exclude:
    # Python 2.6 support has been dropped in Django 1.7
    - python: "2.6"
      env: DJANGO="Django>=1.7,<1.8"
    - python: "2.6"
      env: DJANGO="Django>=1.8,<1.9"
    - python: "2.6"
      env: DJANGO="Django>=1.9,<1.10"
    - python: "2.6"
      env: DJANGO="Django>=1.10,<1.11"
    - python: "2.6"
      env: DJANGO="Django>=1.11,<2.0"
    - python: "2.6"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
    - python: "2.7"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
    - python: "3.4"
      env: DJANGO="Django>=1.4,<1.5"
    - python: "3.4"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
    - python: "3.5"
      env: DJANGO="Django>=1.4,<1.5"
    - python: "3.5"
      env: DJANGO="Django>=1.5,<1.6"
    - python: "3.5"
      env: DJANGO="Django>=1.6,<1.7"
    - python: "3.5"
      env: DJANGO="Django>=1.7,<1.8"
    - python: "3.6"
      env: DJANGO="Django>=1.4,<1.5"
    - python: "3.6"
      env: DJANGO="Django>=1.5,<1.6"
    - python: "3.6"
      env: DJANGO="Django>=1.6,<1.7"
    - python: "3.6"
      env: DJANGO="Django>=1.7,<1.8"
    - python: "3.6"
      env: DJANGO="Django>=1.8,<1.9"
    - python: "3.6"
      env: DJANGO="Django>=1.9,<1.10"
    - python: "3.6"
      env: DJANGO="Django>=1.10,<1.11"
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
